name: vortaro
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.5
  path_provider: ^2.0.13
  sqflite_common_ffi: ^2.2.1+1
  translator: ^0.1.7
  google_nav_bar: ^5.0.6

  injectable: ^1.5.3
  get_it: ^7.2.0
  injectable_generator: ^1.5.4
  dio: ^4.0.6
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_bloc: ^8.1.1
  json_serializable: ^6.5.1
  hydrated_bloc: ^8.1.0
  pretty_dio_logger: ^1.1.1

  json_annotation: ^4.8.0
  flutter_tts: ^3.2.2
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  flutter_local_notifications: ^14.0.0+1
  flutter_timezone: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/dbMain.db
    - assets/images/flagEsp.png


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: Unna
      fonts:
        - asset: assets/fonts/unna/Unna-Regular.ttf
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura/Jura-Regular.ttf
        - asset: assets/fonts/Jura/Jura-Bold.ttf